# Generated by Django 4.2 on 2025-06-24 13:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('medicine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoaDonModel',
            fields=[
                ('MaHoaDon', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('NgayLap', models.DateField(default=django.utils.timezone.now, verbose_name='Ngày lập hóa đơn')),
                ('TongTien', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Tổng tiền')),
                ('MaKH', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hoadon', to='users.khachhangmodel', verbose_name='Khách hàng')),
            ],
        ),
        migrations.CreateModel(
            name='ChiTietHoaDonModel',
            fields=[
                ('MaChiTietHD', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('SoLuongBan', models.PositiveIntegerField(default=1, verbose_name='Số lượng bán')),
                ('GiaBan', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Giá bán')),
                ('MaHoaDon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chitiethoadon', to='invoice.hoadonmodel', verbose_name='Hóa đơn')),
                ('MaThuoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine.thuocmodel', verbose_name='Thuốc')),
            ],
        ),
    ]
