# Generated by Django 4.2 on 2025-06-01 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KhachHang',
            fields=[
                ('MaKhachHang', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('TenKhachHang', models.CharField(max_length=100)),
                ('SoDienThoai', models.CharField(max_length=15)),
                ('DiaChi', models.CharField(max_length=200)),
            ],
        ),
    ]
