# Generated by Django 4.2 on 2025-06-05 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KhachHangModel',
            fields=[
                ('MaKhachHang', models.AutoField(primary_key=True, serialize=False)),
                ('TenKhachHang', models.CharField(max_length=100)),
                ('SoDienThoai', models.CharField(max_length=15)),
                ('DiaChi', models.CharField(max_length=255)),
            ],
        ),
    ]
