# Generated by Django 4.2 on 2025-06-07 01:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KhachHangModel',
            fields=[
                ('MaKhachHang', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('TenKhachHang', models.CharField(blank=True, max_length=100)),
                ('SoDienThoai', models.CharField(blank=True, max_length=15)),
                ('DiaChi', models.CharField(max_length=255)),
            ],
        ),
    ]
