# Generated by Django 4.2 on 2025-07-03 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='khachhangmodel',
            name='SoDienThoai',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='khachhangmodel',
            name='TenKhachHang',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
