# Generated by Django 4.2 on 2025-06-14 13:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicine_types', '0002_alter_loaithuocmodel_donvitinh'),
        ('suppliers', '0001_initial'),
        ('manufacturers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThuocModel',
            fields=[
                ('MaThuoc', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('TenThuoc', models.CharField(blank=True, max_length=100)),
                ('CongDung', models.TextField(blank=True)),
                ('DonGia', models.DecimalField(decimal_places=2, max_digits=12)),
                ('SoLuongTonKho', models.PositiveIntegerField(default=0)),
                ('HanSuDung', models.DateField()),
                ('MaHangSX', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thuoc', to='manufacturers.hangsxmodel')),
                ('MaLoai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thuoc', to='medicine_types.loaithuocmodel')),
                ('MaNCC', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thuoc', to='suppliers.nhacungcapmodel')),
            ],
        ),
    ]
