# Generated by Django 4.2 on 2025-06-14 10:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoaiThuocModel',
            fields=[
                ('MaLoai', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('TenLoai', models.CharField(blank=True, max_length=100)),
                ('DonViTinh', models.CharField(choices=[('viên', 'Viên'), ('lọ', 'Lọ'), ('ống', 'Ống'), ('chai', 'Chai'), ('hộp', 'Hộp')], default='viên', max_length=10)),
            ],
        ),
    ]
